### ISSUE TITLE
Custom Font

### ISSUE THREAD

**Issue by andresantana-dev** [ZhgChgLi/ZMarkupParser#28]
Hello,

It's possible to set a custom font to regular text or to bold tag?
I'm using the MarkupStyle, but it's only changing the size, not the font.

Thanks.

**Comment by zhgchgli0718** [comment]
If you only want to set the width of the font (regular/weight), you can do so by setting the font property in MarkupStyleFont, like this: `MarkupStyleFont(size: CGFloat? = nil, weight: FontWeight? = .style(.bold), italic: Bool? = nil)`.

If you want to set the font family, it is currently not possible to convert CSS Font to iOS UIFont (because they are based on different operating systems, and platform considerations would need to be taken into account if this were to be implemented).

**Comment by zhgchgli0718** [comment]
released @ v1.5.0

**Comment by andresantana-dev** [comment]
Thanks a lot!
