### ISSUE TITLE
Line breaks issue

### ISSUE THREAD

**Issue by www-r3m1x** [ZhgChgLi/ZMarkupParser#47]
In the following HTML example:

`<p>First line</p><p>Second line</p><br/><p>One empty line above</p><br/><br/><p>2 empty lines above</p>`

should render with a line break after the 'Second line' and before the 'One empty line above' and with two line breaks after the 'One empty line above' and before the '2 empty lines above' is rendered. However, I've noticed when the HTML string is parsed, line breaks are stripped out, so the render ends up like this:
<img width="380" alt="Снимок экрана 2024-02-07 в 16 05 50" src="https://github.com/ZhgChgLi/ZMarkupParser/assets/26358461/3dda183a-9f86-4c91-a184-b83fbe910a7f">
instead of this:
<img width="384" alt="Снимок экрана 2024-02-07 в 16 05 30" src="https://github.com/ZhgChgLi/ZMarkupParser/assets/26358461/ab88ad59-8ef4-4afc-b770-b6a2b25158ea">

Looks like a bug because in version 1.7.0 there was a line break after the 'Second line' and before the 'One empty line above'. But after the 'One empty line above' and before the '2 empty lines above' was only one line break instead of two.

**Comment by zhgchgli0718** [comment]
Thank you for your feedback.
I hadn't considered the context that appears between `<xx>` before.
It has been fixed in version `1.8.1`, and if there are any other issues with line breaks, please report them back to us, thank you.

Currently, we will implement it according to the [browser's logic](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_editor) for line breaks. Here are some of the browser line break logics I have listed:
- `<p></p>` -> `/n`
- `<div><p>`... -> `/n`
- `...<br/></p>` -> `/n`
- `...<br/><br/></p>` -> `/n/n`
- `</p><br/><p>` -> `/n/n`

--

![ZhgChgLi-2024-02-10_00-19-51](https://github.com/ZhgChgLi/ZMarkupParser/assets/33706588/7ee367d0-ce01-4523-b429-cd2aed4e2751)
ref: #40

**Comment by www-r3m1x** [comment]
@zhgchgli0718 Thanks! Will you bump version in podspec?

**Comment by zhgchgli0718** [comment]
The pod version has been released.

**Comment by EgorVeremeychik** [comment]
Hello @zhgchgli0718
As I can see
<p></p> -> /n
it's not fully correct logic

<img width="1002" alt="Screenshot 2024-02-23 at 13 58 03" src="https://github.com/ZhgChgLi/ZMarkupParser/assets/46027775/e7466c77-8c6b-4dc7-b95c-2cb62a72fece">

As you can see, <p></p> adds some spacing before and after string
